### ISSUE TITLE
[Feat/Design] 볼링 인터렉션 기능 추가

### ISSUE THREAD

**Issue by jincode93** [DeveloperAcademy-POSTECH/MC3-TEAM14-PPOLROLRO#27]
### 📷 스크린샷
- 추가 예정
---

### 📝 작업 목적

- 볼링 인터렉션 기능 및 UIKit View 추가

---

### 🛠️ Tasks

* [ ] 볼링 에셋 추가
* [ ] 볼링 인터렉션 기능 추가
* [ ] 볼링 인터렉션 UIKit View 추가
