### ISSUE TITLE
[Design] MainView 추가 및 레이아웃 작업

### ISSUE THREAD

**Issue by jincode93** [DeveloperAcademy-POSTECH/MC3-TEAM14-PPOLROLRO#3]
### 📷 스크린샷
- 완료 후 추가 예정
---

### 📝 작업 목적

MainView 전체 레이아웃 작업

---

### 🛠️ Tasks

* [x] MainView 레이아웃 작업
* [x] MainView에 필요한 이미지에셋 추가 및 폴더링
* [x] 템플릿 폴더 열고 닫기 기능 추가
* [x] 부분 스크롤 추가
* [ ] 스크롤 컨트롤 추가
* [ ] 당일 요일 받아와서 지기 위치 변화 기능 추가
* [ ] 당일 요일 받아와서 문구 변화 기능 추가
* [ ] 템플릿 종류에 따라 버튼 문구 변화 기능 추가

**Comment by jincode93** [comment]
- 스크린샷
<img src="https://github.com/DeveloperAcademy-POSTECH/MC3-TEAM14-PPOLROLRO/assets/111134273/7388176b-84ce-4917-9c9a-73511213fb08.png" width="30%" height="30%"/>
