### ISSUE TITLE
[Refactor] 전체 뷰 연결 작업 및 세부 레이아웃 조정

### ISSUE THREAD

**Issue by jincode93** [DeveloperAcademy-POSTECH/MC3-TEAM14-PPOLROLRO#37]
### 📷 스크린샷
- 추가 예정
---

### 📝 작업 목적

- 전체 뷰 연결 작업 및 세부 레이아웃 조정

---

### 🛠️ Tasks

* [ ] 전체 뷰 연결 작업
* [ ] 뷰 단위의 기능 연결 작업
* [ ] 전체 레이아웃 세부 조정
