### ISSUE TITLE
[Feat] SlingShot Interaction 구현

### ISSUE THREAD

**Issue by Suppppppp** [DeveloperAcademy-POSTECH/MC3-TEAM14-PPOLROLRO#38]
### 📷 스크린샷

![Simulator Screen Recording - iPhone 14 Pro - 2023-07-31 at 20 34 29](https://github.com/DeveloperAcademy-POSTECH/MC3-TEAM14-PPOLROLRO/assets/42464602/1f473c7b-8d9b-43fa-9fe7-45c25d5cabad)

---

### 📝 작업 목적

- SlingShot Interaction Game Scene을 구현합니다.

---

### 🛠️ Tasks

* [x] 새총 줄(Line)을 당기면 당긴 방향으로 휘어짐
* [x] 새총 줄(Line)을 놓았을 때 놓은 방향으로 물체가 날라감
* [x] 물체(캐릭터)와 새총 줄(Line)을 연결
* [x] 날라가서 object와 충돌
* [x] 충돌시 효과 및 소리 
* [x] 충돌 횟수 반영 업데이트
* [x] SpritKit을 SwiftUI View로 Wrapping
