### ISSUE TITLE
[Design] MainView 레이아웃 및 동작 방식 수정

### ISSUE THREAD

**Issue by jincode93** [DeveloperAcademy-POSTECH/MC3-TEAM14-PPOLROLRO#56]
### 📷 스크린샷
- 추가 예정
---

### 📝 작업 목적

- MainView 레이아웃 및 동작 방식 수정

---

### 🛠️ Tasks

* [ ] MainView 레이아웃 수정
* [ ] View 작동 방식 수정
* [ ] NavigationView, Link 전체 수정
