### ISSUE TITLE
[Feat/Design] 다트 인터랙션 기능 작업

### ISSUE THREAD

**Issue by ge-um** [DeveloperAcademy-POSTECH/MC3-TEAM14-PPOLROLRO#6]
### 📷 스크린샷

---

### 📝 작업 목적

다트 인터랙션 기능을 작업합니다. 

---

### 🛠️ Tasks

* [x] 캐릭터 이미지 변경
* [x] 폰트 적용 수정
* [x] 레이아웃 만들기
* [x] 핸드폰의 움직임을 이용해 다트가 움직이도록 만들기(coreMotion)
* [x] 다트판과 충돌 시 꽂히는 효과 구현하기
* [x] 앞의 다트는 꽂힌 채로 내버려 둔 채 새로운 다트 생성하기
* [x] 화면을 넘어가면 새로운 다트 생성하기
* [x] 사운드 넣기
* [x] 햅틱 넣기
---
### 미완성
* [ ] 게이지 바 다트가 움직일 때 변화하게 만들기
* [ ] 다트가 움직일 때 날린 갯수 카운트 올라가게 만들기
* [ ] 레이아웃 미세 조정
* [ ] 게이지 바/ 날린 갯수 색상 변경
* [ ] 진입 시 안내 메시지 띄우기
