### ISSUE TITLE
[Design] 볼링 뷰 레이아웃 작업 및 스유로 감싸기

### ISSUE THREAD

**Issue by ge-um** [DeveloperAcademy-POSTECH/MC3-TEAM14-PPOLROLRO#63]
### 📷 스크린샷

---

### 📝 작업 목적

볼링 인터랙션 부분을 스유로 감싼 후 레이아웃 작업을 하려고 합니다. 
---

### 🛠️ Tasks

* [x] 볼링 인터랙션 부분 스유로 감싸기
* [x] 볼링 에셋 교체
* [x] 인터랙션 선택 연결
* [x] 레이아웃 작업 하기
* [x] 컬러 에셋 교체
