### ISSUE TITLE
[Design] 인터렉션 트렌지션 4단계 뷰 추가 및 레이아웃 작업

### ISSUE THREAD

**Issue by jincode93** [DeveloperAcademy-POSTECH/MC3-TEAM14-PPOLROLRO#7]
### 📷 스크린샷

- 추가 예정

---

### 📝 작업 목적

- 인터렉션 트렌지션 4단계 뷰 추가 및 레이아웃 작업

---

### 🛠️ Tasks

* [x] 인터렉션 트렌지션 뷰 4가지 추가
* [x] 인터렉션 트렌지션 뷰 에셋 추가
* [x] 첫번째 인터렉션 트렌지션 뷰 드래그 동작 구현
* [ ] 두번쩨, 세번째, 네번째 인터렉션 트렌지션 뷰 탭 동작 구현
* [ ] 자동 네비게이션 구현

**Comment by jincode93** [comment]
- 디자인팀 플로우 수정으로 인해 연기
