### ISSUE TITLE
[Feat] 최근 폴더/ 보관함 ImageData를 위한 CoreData구축

### ISSUE THREAD

**Issue by Suppppppp** [DeveloperAcademy-POSTECH/MC3-TEAM14-PPOLROLRO#77]
### 📷 스크린샷
- Dummy View에 연결한 CoreData 시연영상

![Simulator Screen Recording - iPhone 14 Pro - 2023-08-02 at 20 33 55](https://github.com/DeveloperAcademy-POSTECH/MC3-TEAM14-PPOLROLRO/assets/42464602/d6eef479-c107-4e2a-aced-cebdd198512f)

---

### 📝 작업 목적

- 작성한 사직서들의 최근 내용을 최근 폴더에 저장
  - 최근 작성한 사직서는 총 5개만 유지
  - FIFO(선입선출)로 사직서 교체
  - 이미지 자체를 data로 변환해서 CoreData에 저장

- 작성한 사직서들과 해당 사직서로 Interaction을 해서 받은 보상카드를 보관함에 저장
  - 위의 사직서와 별도 취급
    - 이유는 최근 사직서는 사직서를 작성할때마다 바뀌지만 보관함은 정말 보관을 위하고 다시보기 위한 목적
    - 사직서가 없어도 Interaction은 할 수 있는데 이 때 빈 사직서 화면과 보상카드가 한 세트 (Pair)
  - FIFO(선입선출)로 10개만 유지
  - 이미지 자체를 data로 변환해서 CoreData에 저장

---

### 🛠️ Tasks

* [x] View ImageRendering
* [x] CoreData설정 (Entity와 해당 Entity의 Attributes)
* [x] Rendering 한 Image를 Data의 형태로 CoreData저장
   * [x] Fetch() 구현
   * [x] Add() 구현
   * [x] Save() 구현
   * [x] Delete() 구현
* [x] View와 ViewModel 분리를 위해 View자체가 함수의 input으로 들어가게 설정
   * [x] Model 설정 (PairSet)
