### ISSUE TITLE
[Feat] Template선택 후 내용 편집화면(TemplateEditorView) 추가

### ISSUE THREAD

**Issue by Suppppppp** [DeveloperAcademy-POSTECH/MC3-TEAM14-PPOLROLRO#9]
### 📷 스크린샷
- 현재 구현된 것 상태까지의 화면입니다.

![Simulator Screen Recording - iPhone 14 Pro - 2023-07-28 at 05 38 23](https://github.com/DeveloperAcademy-POSTECH/MC3-TEAM14-PPOLROLRO/assets/42464602/4705c83f-b603-484e-9b80-c93c5c9b95a1)

---

### 📝 작업 목적

- 템플릿 선택 후 화면에 내용을 작성합니다.
- 작업한 View를 통합하기 위해 깃헙에 올려놓습니다
- 앱의 최상단(@main) 파일에 화면 구현을 위한 .environmentObject 설정 
- MVVM의 형식을 따르고 View,Model,ViewModel로 구성
    -  추가된 화면 : 
        - View - [ SelectedTemplateView, TemplatesEditorView, TextEditorView, TextDragGesture, TextColorPicker]
        - Model - [ TextBoxModel ]
        - ViewModel - [ TemplatesEditorViewModel ]
- 현재 완료되지 않은 것
    -  화면 레이아웃 ( View를 합치는 쪽인 제롬이 진행해주시기로 함)
---

### 🛠️ Tasks

* [x] 템플릿 View위치에 텍스트 입력
* [x] 글씨 작성을 위한 View가 템플릿 View위에 나타나기 
* [x] 입력한 텍스트를 드래그하기
* [x] 입력한 텍스트 터치시 수정화면 팝업 & 수정
* [x] 입력한 글자들 전체 삭제
* [x] 텍스트 색깔 변경
