### ISSUE TITLE
[Design] 인터랙션 레이아웃 전체 점검 및 수정

### ISSUE THREAD

**Issue by ge-um** [DeveloperAcademy-POSTECH/MC3-TEAM14-PPOLROLRO#96]
### 📷 스크린샷

---

### 📝 작업 목적

빠져먹은 부분이 몇 개 있어서 다시 작업합니다. 
---

### 🛠️ Tasks

* [x] 게임 안내 화면 뒤쪽 검정색으로 만들기
* [x] 새총 내비게이션에 글씨 색 수정
* [x] 날린 사직서 갯수 글씨 색 바꾸기
* [x] 컴포넌트 높이 통일시키기
